### PR TITLE
Remove crypto and upgrade dart sdk to 1.13.0

### PR DESCRIPTION
**Pull request by enyo**

### CODE REVIEW

**Comment by sgjesse** [comment]
This looks fine to me, Brian (@skybrian), can you take a look?

**Comment by srawlins** [comment]
Looks like @kevmoo did this in https://github.com/dart-lang/dart-protobuf/commit/17859c7356a8670c8a580992e7145d0f48a1db70.

**Comment by kevmoo** [comment]
Yup! @enyo inspired me. Thansk, much.

**Comment by zoechi** [comment]
Somehow this broke pub

**Comment by skybrian** [comment]
Could you be more specific?

**Comment by zoechi** [comment]
@skybrian sorry, see the issue dart-lang/pub#1410 (linked above)

**Pull request closed without merging**
